# Generated by Django 4.2 on 2025-05-06 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="allergy",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="allergy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="labresult",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="labresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="blood_type",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="medication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aianalysis",
            name="analysis_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="allergen",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="severity",
            field=models.CharField(
                choices=[
                    ("mild", "Mild"),
                    ("moderate", "Moderate"),
                    ("severe", "Severe"),
                ],
                default="mild",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="reference_range",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="result_value",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="test_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="condition",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="diagnosis_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_histories",
                to="medical_records.medicalrecord",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="MedicalImage",
        ),
    ]
