# Generated by Django 4.2 on 2025-05-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_consultation_doctor_offers_online_consultation_and_more"),
        (
            "medical_records",
            "0002_aianalysis_created_at_aianalysis_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="medical_documents/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("medical_report", "Rapport Médical"),
                            ("lab_result", "Résultat d'Analyse"),
                            ("prescription", "Prescription"),
                            ("imaging", "Imagerie"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_type", models.CharField(max_length=100)),
                ("image_date", models.DateField()),
                ("image_file", models.ImageField(upload_to="medical_images/")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("hospital", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "doctors",
                    models.ManyToManyField(
                        related_name="performed_operations", to="users.doctor"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="allergy",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="allergy",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="labresult",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="labresult",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="blood_type",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="vitalsign",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="vitalsign",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="allergy",
            name="allergen",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="severity",
            field=models.CharField(
                choices=[
                    ("mild", "Légère"),
                    ("moderate", "Modérée"),
                    ("severe", "Sévère"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="reference_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="result_value",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="test_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="condition",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="diagnosis_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_entries",
                to="medical_records.medicalrecord",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_record",
                to="users.patient",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="AIAnalysis",
        ),
        migrations.AddField(
            model_name="operation",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="medical_records.medicalrecord",
            ),
        ),
        migrations.AddField(
            model_name="medicalimage",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_images",
                to="medical_records.medicalrecord",
            ),
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="medical_records.medicalrecord",
            ),
        ),
    ]
