# Generated by Django 4.2 on 2025-05-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0007_patient_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrainScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="brain_scans/")),
                ("result", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brain_scans",
                        to="users.patient",
                    ),
                ),
            ],
        ),
    ]
