# Generated by Django 4.2 on 2025-05-23 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0003_medicaldocument_medicalimage_operation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brain_diagnostics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brainscan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Brain Scan",
                "verbose_name_plural": "Brain Scans",
            },
        ),
        migrations.AddField(
            model_name="brainscan",
            name="medical_record",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brain_scans",
                to="medical_records.medicalrecord",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brainscan",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="brainscan",
            name="confidence",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brainscan",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brain_scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="brainscan",
            name="result",
            field=models.CharField(max_length=100),
        ),
    ]
