# Generated by Django 4.2 on 2025-05-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_patient_profile_picture"),
        (
            "brain_diagnostics",
            "0002_alter_brainscan_options_brainscan_medical_record_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brainscan",
            options={},
        ),
        migrations.RemoveField(
            model_name="brainscan",
            name="medical_record",
        ),
        migrations.RemoveField(
            model_name="brainscan",
            name="notes",
        ),
        migrations.AlterField(
            model_name="brainscan",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="brainscan",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brain_scans",
                to="users.patient",
            ),
        ),
        migrations.AlterField(
            model_name="brainscan",
            name="result",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
