# Generated by Django 4.2 on 2025-05-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
