# Generated by Django 4.2 on 2025-05-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_doctor_address_doctor_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="availability",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="consultation_duration",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="doctor",
            name="notifications_settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="other_specialties",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="license_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
