# Generated by Django 4.2 on 2025-05-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0003_medicaldocument_medicalimage_operation_and_more"),
        ("users", "0005_consultation_doctor_offers_online_consultation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="medical_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="medical_records.medicalrecord",
            ),
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
    ]
